version: 2
jobs:
  runs:
    docker:
      - image: circleci/node:11
    working_directory: ~/llct_circleci
    steps:
      - checkout
      - run:
          name: Downloading Github Pages CLI
          command: sudo npm install gh-pages --unsafe-perm -g
      - run:
          name: Downloading Dependencies
          command: yarn
      - run:
          name: Gulp Building
          command: yarn build
      - run:
          name: Git Settings
          command: |
            git config --global user.email $GIT_EMAILS
            git config --global user.name $GIT_NAME
      - add_ssh_keys:
          fingerprints:
            - "50:ff:23:2d:9f:a5:df:01:0d:6b:67:d5:37:e5:50:20"
      - run:
          name: Deploying to Github PAges
          command: yarn deploy

workflows:
  version: 2
  build_and_tests:
    jobs:
      - runs
