version: 2.1
machine:
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
dependencies:
  override:
    - node_modules/.bin/yarn
  pre:
    - yarn global add now

jobs:
  build:
    steps:
      - run:
          name: Building
          command: "yarn build"
  test:
    steps:
      - run:
          name: "Testing"
          command: "yarn test"
  deploy:
    environment:
      NOW_TOKEN:
    steps:
      - run:
          name: Deploying to now.sh
          command: |
            cd ./dist/
            now -t ${NOW_TOKEN}

workflows:
  version: 2.1
  deploy:
    jobs:
      - build
      - test:
        requires:
          - build
        filters:
          branches:
            only: master
      - deploy
