version: 2
jobs:
  runs:
    docker:
      - image: circleci/node:11
    working_directory: ~/llct_circleci
    steps:
      - checkout
      - run:
          name: Downloading Github Pages CLI
          command: sudo npm install gh-pages --unsafe-perm -g
      - run:
          name: Downloading Dependencies
          command: yarn
      - run:
          name: Gulp Building
          command: yarn build
      - run:
          name: Git Settings
          command: |
            git config --global user.email $GIT_EMAILS
            git config --global user.name $GIT_NAME
      - add_ssh_keys:
          fingerprints:
            - "c6:30:16:76:cb:86:3e:ff:bb:60:37:b7:4a:7e:28:08"
      - run:
          name: Deploying to Github PAges
          command: yarn deploy

workflows:
  version: 2
  build_and_tests:
    jobs:
      - runs
